package com.sengine.project

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import com.sengine.engine.anim.AnimationClip
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.io.FileOutputStream
import java.util.zip.ZipInputStream

/**
 * The engine's offline Asset Store.
 *
 * Content comes from the ZIPs in the repository's `Assets/` folder, which Gradle
 * packs into the APK (see `assets.srcDir("$rootDir/Assets")` in
 * app/build.gradle.kts).  Nothing here touches the network.
 *
 * Two files drive it:
 *
 *  * `assets/store/store_manifest.json` - generated by `tools/build_asset_store.py`.
 *    Describes every pack and every file in it, including pixel dimensions and
 *    auto-detected sprite-sheet grids.  ~750 KB, parsed once and cached.
 *  * `assets/<pack>.zip` - the pack payload, extracted to
 *    `filesDir/store/<packId>/` the first time anything from it is used.
 *
 * Packs are extracted lazily and individually: the store ships ~60 MB of ZIPs,
 * and unpacking all of it at first launch would waste both time and storage on
 * a phone.
 */
object AssetStore {

    // ------------------------------------------------------------------ model
    class Sheet(val frameW: Int, val frameH: Int, val cols: Int, val rows: Int,
                val frames: Int, val guess: Boolean)

    class Entry(
        val path: String,
        val name: String,
        val ext: String,
        val bytes: Long,
        val kind: String,
        val category: String,
        val w: Int,
        val h: Int,
        val sheet: Sheet?,
    ) {
        val isImage get() = kind == "image"
        val isAudio get() = kind == "audio"
        val isModel get() = kind == "model"
        val dimensionLabel get() = if (w > 0) "${w}x${h}" else ext.uppercase()
        val sizeLabel get() = when {
            bytes >= 1_048_576 -> String.format("%.1f MB", bytes / 1_048_576.0)
            bytes >= 1024 -> String.format("%.0f KB", bytes / 1024.0)
            else -> "$bytes B"
        }
        /** Stable key for caches and "already in project" checks. */
        val key get() = path
    }

    class Pack(
        val id: String,
        val title: String,
        val zip: String,          // original filename in the repo's Assets/
        val zipAsset: String,     // safe filename as packaged into the APK
        val zipBytes: Long,
        val kind: String,
        val license: String,
        val author: String,
        val distributable: Boolean,
        val tags: List<String>,
        val fileCount: Int,
        val bytes: Long,
        val categories: Map<String, Int>,
        val files: List<Entry>,
    ) {
        val imageCount get() = files.count { it.isImage }
        val sheetCount get() = files.count { it.sheet != null }
        val primaryCategory get() = categories.maxByOrNull { it.value }?.key ?: "Textures"
    }

    class Manifest(
        val schema: Int,
        val generatedAt: String,
        val totals: Map<String, Long>,
        val categoryOrder: List<String>,
        val categoryTotals: Map<String, Int>,
        val packs: List<Pack>,
    ) {
        val entries: List<Entry> get() = packs.flatMap { it.files }
    }

    class ImportResult(val imported: Int, val clips: Int, val skipped: Int, val errors: List<String>) {
        val ok get() = errors.isEmpty()
    }

    // ------------------------------------------------------------------ state
    private var cached: Manifest? = null
    private val thumbCache = LinkedHashMap<String, Bitmap>(32, 0.75f, true)
    private const val THUMB_CACHE_MAX = 96

    const val MANIFEST_ASSET = "store/store_manifest.json"

    // ------------------------------------------------------------------ paths
    /** Where extracted packs live. Deleted by "clear store cache". */
    fun storeDir(ctx: Context) = File(ctx.filesDir, "store").also { it.mkdirs() }

    fun packDir(ctx: Context, pack: Pack) = File(storeDir(ctx), pack.id)

    /** Marker written after a successful extract so a partial one is retried. */
    private fun stamp(ctx: Context, pack: Pack) = File(packDir(ctx, pack), ".extracted")

    fun isExtracted(ctx: Context, pack: Pack) = stamp(ctx, pack).exists()

    fun extractedBytes(ctx: Context, pack: Pack): Long =
        if (!isExtracted(ctx, pack)) 0L
        else packDir(ctx, pack).walkTopDown().filter { it.isFile }.sumOf { it.length() }

    // ------------------------------------------------------------------ load
    fun load(ctx: Context): Manifest {
        cached?.let { return it }
        val text = ctx.assets.open(MANIFEST_ASSET).bufferedReader().use { it.readText() }
        val m = parseManifest(JSONObject(text))
        cached = m
        return m
    }

    fun parseManifest(o: JSONObject): Manifest {
        val totals = o.optJSONObject("totals")?.let { t ->
            t.keys().asSequence().associateWith { t.optLong(it) }
        } ?: emptyMap()

        val catOrder = o.optJSONArray("categories")?.let { a ->
            (0 until a.length()).map { a.getString(it) }
        } ?: emptyList()

        val catTotals = o.optJSONObject("categoryTotals")?.let { c ->
            c.keys().asSequence().associateWith { c.optInt(it) }
        } ?: emptyMap()

        val packs = o.optJSONArray("packs")?.let { arr ->
            (0 until arr.length()).map { parsePack(arr.getJSONObject(it)) }
        } ?: emptyList()

        return Manifest(o.optInt("schema", 1), o.optString("generatedAt"), totals,
            catOrder, catTotals, packs)
    }

    private fun parsePack(o: JSONObject): Pack {
        val cats = o.optJSONObject("categories")?.let { c ->
            c.keys().asSequence().associateWith { c.optInt(it) }
        } ?: emptyMap()

        val tags = o.optJSONArray("tags")?.let { a ->
            (0 until a.length()).map { a.getString(it) }
        } ?: emptyList()

        val files = o.optJSONArray("files")?.let { arr ->
            (0 until arr.length()).map { parseEntry(arr.getJSONObject(it)) }
        } ?: emptyList()

        return Pack(
            o.optString("id"), o.optString("title"), o.optString("zip"),
            o.optString("zipAsset", o.optString("id") + ".zip"),
            o.optLong("zipBytes"), o.optString("kind", "2d"), o.optString("license"),
            o.optString("author"), o.optBoolean("distributable", true), tags,
            o.optInt("fileCount", files.size), o.optLong("bytes"), cats, files,
        )
    }

    private fun parseEntry(o: JSONObject): Entry {
        val sheet = o.optJSONObject("sheet")?.let {
            Sheet(it.optInt("frameW"), it.optInt("frameH"), it.optInt("cols"),
                it.optInt("rows"), it.optInt("frames"), it.optBoolean("guess", false))
        }
        return Entry(
            o.optString("path"), o.optString("name"), o.optString("ext"),
            o.optLong("bytes"), o.optString("kind", "other"), o.optString("category", "Textures"),
            o.optInt("w", 0), o.optInt("h", 0), sheet,
        )
    }

    // ------------------------------------------------------------- extraction
    /**
     * Normalises a ZIP entry name to a manifest path.
     *
     * Must stay in lock-step with `safe_member_name` / `strip_root` in
     * tools/build_asset_store.py: several packs were authored on Windows and
     * store paths like `screenshots\01_hero.png` as a single filename, and most
     * wrap everything in one folder that repeats the ZIP name.
     */
    internal fun normalizeEntryName(raw: String): String? {
        val parts = raw.replace('\\', '/').split('/')
            .filter { it.isNotEmpty() && it != "." && it != ".." }
        if (parts.isEmpty()) return null
        if (parts[0] == "__MACOSX") return null
        val last = parts.last()
        if (last.startsWith("._") || last == ".DS_Store" || last.endsWith("~")) return null
        return parts.joinToString("/")
    }

    /** Drops a single common wrapper folder, matching the generator. */
    internal fun stripRoot(names: List<String>): Pair<List<String>, String?> {
        if (names.isEmpty()) return names to null
        val roots = names.map { it.substringBefore('/', "") }.filter { it.isNotEmpty() }.toSet()
        return if (roots.size == 1 && names.all { '/' in it }) {
            val root = roots.first()
            names.map { it.substring(root.length + 1) } to root
        } else names to null
    }

    /**
     * Extracts [pack] on first use.  Safe to call repeatedly; a pack whose
     * previous extraction was interrupted (no stamp) is redone from scratch.
     */
    @Synchronized
    fun extract(ctx: Context, pack: Pack, onProgress: ((Int, Int) -> Unit)? = null): File {
        val dir = packDir(ctx, pack)
        if (isExtracted(ctx, pack)) return dir

        if (dir.exists()) dir.deleteRecursively()
        dir.mkdirs()

        // First pass maps zip entry -> manifest path so the wrapper folder can
        // be detected exactly the way the generator detected it.
        val wanted = pack.files.associateBy { it.path }
        val mapping = HashMap<String, String>()
        ctx.assets.open(pack.zipAsset).use { input ->
            ZipInputStream(input.buffered()).use { zip ->
                val normalized = ArrayList<Pair<String, String>>()   // raw -> normalised
                var e = zip.nextEntry
                while (e != null) {
                    if (!e.isDirectory) {
                        normalizeEntryName(e.name)?.let { normalized.add(e.name to it) }
                    }
                    zip.closeEntry()
                    e = zip.nextEntry
                }
                val (stripped, _) = stripRoot(normalized.map { it.second })
                for (i in normalized.indices) {
                    val target = stripped[i]
                    if (wanted.containsKey(target)) mapping[normalized[i].first] = target
                }
            }
        }

        var done = 0
        val total = mapping.size
        ctx.assets.open(pack.zipAsset).use { input ->
            ZipInputStream(input.buffered()).use { zip ->
                var e = zip.nextEntry
                while (e != null) {
                    val target = if (!e.isDirectory) mapping[e.name] else null
                    if (target != null) {
                        val out = File(dir, target)
                        out.parentFile?.mkdirs()
                        FileOutputStream(out).use { fos -> zip.copyTo(fos, 64 * 1024) }
                        done++
                        onProgress?.invoke(done, total)
                    }
                    zip.closeEntry()
                    e = zip.nextEntry
                }
            }
        }

        stamp(ctx, pack).writeText("extracted ${System.currentTimeMillis()}\n$done/$total files\n")
        return dir
    }

    /** File on disk for a manifest entry, or null when the pack is not extracted. */
    fun file(ctx: Context, pack: Pack, entry: Entry): File? {
        if (!isExtracted(ctx, pack)) return null
        val f = File(packDir(ctx, pack), entry.path)
        return if (f.exists()) f else null
    }

    // ------------------------------------------------------------ thumbnails
    /**
     * Decodes a downscaled, pixel-art-friendly thumbnail.  Returns null for
     * non-images, for unextracted packs, and on decode failure.
     */
    fun thumbnail(ctx: Context, pack: Pack, entry: Entry, maxPx: Int = 128): Bitmap? {
        if (!entry.isImage) return null
        thumbCache[entry.key]?.let { return it }

        val f = file(ctx, pack, entry) ?: return null
        val bounds = BitmapFactory.Options().apply { inJustDecodeBounds = true }
        BitmapFactory.decodeFile(f.absolutePath, bounds)
        if (bounds.outWidth <= 0) return null

        var sample = 1
        while (bounds.outWidth / (sample * 2) >= maxPx || bounds.outHeight / (sample * 2) >= maxPx)
            sample *= 2

        val opts = BitmapFactory.Options().apply {
            inSampleSize = sample
            inPreferredConfig = Bitmap.Config.ARGB_8888
        }
        val bmp = BitmapFactory.decodeFile(f.absolutePath, opts) ?: return null
        thumbCache[entry.key] = bmp
        while (thumbCache.size > THUMB_CACHE_MAX) {
            val eldest = thumbCache.entries.iterator().next()
            thumbCache.remove(eldest.key)
        }
        return bmp
    }

    /** Frees decoded thumbnails; call when leaving the store. */
    fun clearThumbnailCache() = thumbCache.clear()

    // ---------------------------------------------------------------- import
    /**
     * Copies entries into [project], flattening the pack's folder layout into
     * the project's single `assets/` directory.  Sprite sheets also get a
     * matching `.anim` clip built from the grid in the manifest, so an imported
     * character is animatable immediately instead of needing manual slicing.
     */
    fun importInto(ctx: Context, project: Project, pack: Pack, entries: List<Entry>,
                   onProgress: ((Int, Int) -> Unit)? = null): ImportResult {
        val errors = ArrayList<String>()
        var imported = 0
        var clips = 0
        var skipped = 0

        try {
            extract(ctx, pack)
        } catch (e: Exception) {
            return ImportResult(0, 0, entries.size, listOf("extract failed: ${e.message}"))
        }

        project.assetsDir.mkdirs()
        val total = entries.size
        entries.forEachIndexed { i, entry ->
            try {
                val src = file(ctx, pack, entry)
                if (src == null) { skipped++; return@forEachIndexed }

                val targetName = project.uniqueAssetName(flatName(entry))
                val dest = project.assetFile(targetName)
                src.copyTo(dest, overwrite = true)
                imported++

                val s = entry.sheet
                if (s != null && s.cols >= 1 && s.rows >= 1 && s.frames >= 2 && !s.guess) {
                    val clipName = project.uniqueAssetName(targetName.substringBeforeLast('.') + ".anim")
                    val clip = AnimationClip(
                        texture = targetName,
                        columns = s.cols,
                        rows = s.rows,
                        frames = (0 until s.frames).toMutableList(),
                        fps = defaultFps(entry),
                        loop = defaultLoop(entry),
                    )
                    project.writeAsset(clipName, clip.toJson().toString(2))
                    clips++
                }
            } catch (e: Exception) {
                errors += "${entry.name}: ${e.message}"
            }
            onProgress?.invoke(i + 1, total)
        }
        return ImportResult(imported, clips, skipped, errors)
    }

    fun importPack(ctx: Context, project: Project, pack: Pack,
                   onProgress: ((Int, Int) -> Unit)? = null) =
        importInto(ctx, project, pack, pack.files, onProgress)

    /**
     * Names a flattened asset.  Pack folders are deep and full of duplicate
     * basenames ("Idle-Sheet.png" appears in eight places), so the immediate
     * parent directory is folded in to keep names both unique and readable.
     */
    internal fun flatName(entry: Entry): String {
        val base = sanitizeSegment(entry.name)
        val parent = entry.path.substringBeforeLast('/', "").substringAfterLast('/')
        return if (parent.isEmpty()) base else "${sanitizeSegment(parent)}_$base"
    }

    private fun sanitizeSegment(s: String) =
        s.replace(Regex("[^A-Za-z0-9._\\-]"), "_").take(64)

    /** One-shot actions should not loop; idle/run cycles should. */
    internal fun defaultLoop(entry: Entry): Boolean {
        val n = entry.path.lowercase()
        return !listOf("death", "dead", "die", "hurt", "attack", "jump", "hit", "vanish", "spawn")
            .any { n.contains(it) }
    }

    internal fun defaultFps(entry: Entry): Float {
        val n = entry.path.lowercase()
        return when {
            n.contains("idle") -> 6f
            n.contains("death") || n.contains("dead") -> 10f
            n.contains("attack") -> 14f
            n.contains("walk") || n.contains("run") || n.contains("move") -> 12f
            else -> 10f
        }
    }

    // ---------------------------------------------------------------- search
    fun search(m: Manifest, query: String, category: String?, packId: String?): List<Pair<Pack, Entry>> {
        val q = query.trim().lowercase()
        val out = ArrayList<Pair<Pack, Entry>>()
        for (p in m.packs) {
            if (packId != null && p.id != packId) continue
            for (e in p.files) {
                if (category != null && e.category != category) continue
                if (q.isNotEmpty() && !e.path.lowercase().contains(q) &&
                    !p.title.lowercase().contains(q) &&
                    p.tags.none { it.contains(q) }) continue
                out += p to e
            }
        }
        return out
    }

    /** Drops every extracted pack, freeing storage. The ZIPs stay in the APK. */
    fun clearCache(ctx: Context) {
        storeDir(ctx).deleteRecursively()
        clearThumbnailCache()
    }
}
