plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "com.sengine"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.sengine.app"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0.0"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            // Signed with the debug key so the release APK is installable out of the box.
            // Replace with your own signing config before publishing.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    testOptions {
        unitTests.isReturnDefaultValues = true
    }
    packaging {
        resources.excludes += setOf("META-INF/DEPENDENCIES", "META-INF/LICENSE*", "META-INF/NOTICE*")
    }

    sourceSets {
        getByName("main") {
            // The offline Asset Store: the ZIPs staged by stageStoreAssets below.
            assets.srcDir(layout.buildDirectory.dir("generated/storeAssets"))
            // The shipped games, staged by stageGameLibrary below.
            assets.srcDir(layout.buildDirectory.dir("generated/gameLibrary"))
        }
    }
}

// ---------------------------------------------------------------------------
// Offline Asset Store packaging.
//
// The store's payload is the set of ZIPs in the repository's Assets/ folder.
// Their real names contain spaces, commas and exclamation marks, which are
// awkward as Android asset names, so they are copied into the build directory
// under the safe "<packId>.zip" names recorded in store/pack_map.txt -- the same
// file tools/build_asset_store.py generates the manifest from, so the two can
// never disagree.
//
// They are copied into build/ rather than committed: the ZIPs already live in
// Assets/, and duplicating ~60 MB into git would be pure waste.
// ---------------------------------------------------------------------------
val storePackMap = file("${rootDir}/app/src/main/assets/store/pack_map.txt")
val storeAssetsDir = layout.buildDirectory.dir("generated/storeAssets")

val stageStoreAssets = tasks.register("stageStoreAssets") {
    group = "sengine"
    description = "Copy Assets/*.zip into the APK under safe asset names."
    inputs.file(storePackMap)
    inputs.dir(file("${rootDir}/Assets"))
    outputs.dir(storeAssetsDir)
    doLast {
        require(storePackMap.exists()) {
            "Missing $storePackMap - run: python3 tools/build_asset_store.py"
        }
        val out = storeAssetsDir.get().asFile.apply { mkdirs() }
        var copied = 0
        var missing = 0
        storePackMap.readLines()
            .filter { it.isNotBlank() && !it.startsWith("#") }
            .forEach { line ->
                val parts = line.split("\t")
                if (parts.size != 2) return@forEach
                val src = file("${rootDir}/Assets/${parts[0]}")
                if (!src.exists()) { missing++; return@forEach }
                src.copyTo(File(out, parts[1]), overwrite = true)
                copied++
            }
        logger.lifecycle("S Engine asset store: staged $copied packs ($missing missing) into $out")
    }
}

// ---------------------------------------------------------------------------
// Shipped game library packaging.
//
// The four games in games/ are plain text (game.json, scenes, scripts) whose art
// comes from the Asset Store at import time, so they cost almost nothing to
// package.  They are copied rather than referenced because android.sourceSets
// cannot filter a srcDir down to a subdirectory.
//
// index.json is generated by tools/build_asset_store.py alongside the manifest,
// so the list of games and the list of validated games cannot disagree.
// ---------------------------------------------------------------------------
val gameLibraryDir = layout.buildDirectory.dir("generated/gameLibrary")

val stageGameLibrary = tasks.register("stageGameLibrary") {
    group = "sengine"
    description = "Copy games/* into the APK assets for GameLibrary."
    inputs.dir(file("${rootDir}/games"))
    outputs.dir(gameLibraryDir)
    doLast {
        val src = file("${rootDir}/games")
        require(src.exists()) { "Missing $src - the shipped game library is not present" }
        val out = gameLibraryDir.get().asFile
        if (out.exists()) out.deleteRecursively()
        out.mkdirs()
        var games = 0
        File(out, "games").mkdirs()
        src.listFiles()?.filter { it.isDirectory }?.sortedBy { it.name }?.forEach { g ->
            if (!File(g, "game.json").exists()) return@forEach
            g.copyRecursively(File(out, "games/${g.name}"), overwrite = true)
            games++
        }
        require(games > 0) { "No games found in $src" }

        // index.json sits *beside* the game directories, so a filter that keeps
        // only directories drops it.  GameLibrary.load() reads games/index.json
        // and falls back to a hardcoded KNOWN_IDS list when it is missing, so the
        // omission is silent: the four shipped games still appear, but the index
        // that tools/build_asset_store.py generates is never actually consulted.
        // A fifth game would be listed by the index and still not show up.
        val index = File(src, "index.json")
        if (index.exists()) {
            index.copyTo(File(out, "games/index.json"), overwrite = true)
            logger.lifecycle("S Engine game library: staged index.json")
        } else {
            logger.warn("S Engine game library: $index is missing; GameLibrary will " +
                    "fall back to its hardcoded KNOWN_IDS list")
        }
        logger.lifecycle("S Engine game library: staged $games games into $out")
    }
}

tasks.named("preBuild") { dependsOn(stageStoreAssets, stageGameLibrary) }

dependencies {
    implementation("androidx.core:core-ktx:1.12.0")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("com.google.android.material:material:1.11.0")
    implementation("androidx.recyclerview:recyclerview:1.3.2")
    // JavaScript scripting runtime (interpreted mode). 1.7.14 breaks on Android (javax.lang.model), keep 1.7.13
    implementation("org.mozilla:rhino:1.7.13")

    testImplementation("junit:junit:4.13.2")
    testImplementation("org.json:json:20231013")
}

tasks.withType<Test>().configureEach {
    testLogging {
        events("failed", "passed")
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showStandardStreams = true
    }
}
